# birds = [
#      "Northern_goshawk",
#      "Eurasian_sparrowhawk",
#      "Marsh_warbler",
#      "Acrocephalus",
#      "Common_reed_warbler",
#      "Common_sandpiper",
#      "Mandarin_duck",
#      "Wood_duck",
#      "Razorbill",
#      "Common_kingfisher",
#      "Northern_pintail",
#      "Northern_shoveler",
#      "Eurasian_teal",
#      "Mallard",
#      "Greylag_goose",
#      "Common_swift",
#      "Golden_eagle",
#      "Short-eared_owl",
#      "Long-eared_owl",
#      "Little_owl",
#      "Common_pochard",
#      "Bohemian_waxwing",
#      "Eurasian_bittern",
#      "Dunlin",
#      "Red_knot",
#      "Long-tailed_nightjar",
#      "European_nightjar",
#      "Common_linnet",
#      "European_goldfinch",
#      "Little_ringed_plover",
#      "Australian_wood_duck",
#      "European_greenfinch",
#      "Western_marsh_harrier",
#      "Hen_harrier",
#      "Great_spotted_woodpecker",
#      "Eurasian_jay",
#      "Eurasian_oystercatcher",
#      "Common_gull",
#      "Black-tailed_gull",
#      "Lesser_black-backed_gull",
#      "Red_kite",
#      "Common_pheasant",
#      "Greater_flamingo",
#      "European_green_woodpecker",
#      "Grey_plover",
#      "Bornean_peacock-pheasant",
#      "Tawny_owl",
#      "Western_capercaillie",
#      "Common_redshank",
#      "Barn_owl",
#      "Asian-Green-Bee-Eater",
#      "Brown-Headed-Barbet",
#      "Cattle-Egret",
#      "Common-Kingfisher",
#      "Common-Myna",
#      "Common-Rosefinch",
#      "Common-Tailorbird",
#      "Coppersmith-Barbet",
#      "Forest-Wagtail",
#      "Gray-Wagtail",
#      "Hoopoe",
#      "House-Crow",
#      "Indian-Grey-Hornbill",
#      "Indian-Peacock",
#      "Indian-Pitta",
#      "Indian-Roller",
#      "Jungle-Babbler",
#      "Northern-Lapwing",
#      "Red-Wattled-Lapwing",
#      "Ruddy-Shelduck",
#      "Rufous-Treepie",
#      "Sarus-Crane",
#      "White-Breasted-Kingfisher",
#      "White-Breasted-Waterhen",
#      "White-Wagtail",
#      "Platanus",
#      "Podocarpus_macrophyllus"
# ]

birds = [
    "House_crow",
    "Peafowl",
    "Eurasian_goshawk",
    "Long-eared_owl",
    "Bronzed_drongo",
    "Asian_koel",
    "Purple_sunbird",
    "Zelkova_serrata",
    "Triadica_sebifera"
]